export const debugData = {
  Azure: [
    "azur lane",
    "window",
    "ray",
    "vixen チュウニズム",
    "devops server",
    "meaning",
    "bentley  for men",
    "dip powder",
    "sentinel",
    "iot",
    "(バンド)",
    "mountain",
    "beauty dip powder",
    "blob storage",
    "devops",
    "moon",
    "storage",
    "data studio",
    "-hooded jay",
    "ア 牛王",
    "(heraldry)",
    "(アルバム)",
    "asmr",
    "dragon",
    "うがい薬",
    "うがい液",
    "ad",
    "standard",
    "portal",
    "ア",
    "beauty dip powder nail kit",
    "ad connect",
    "フィギュア",
    "cost calculator",
    "data factory",
    "(color)",
    "beauty nail dip powder",
    "portal ログイン",
    "striker gunvolt 3",
    "microsoft",
    "まとめ",
    "arc",
    "active directory",
    "storage explorer download",
    "ア 紅姫",
    "♯",
    "bgm",
    "storage explorer",
    "arbitrator",
    "速報",
    "sphere",
    "アの家ミートピア",
    "アの家",
    "front door",
    "dip powder liquid set",
    "markers",
    "key vault",
    "blue",
    "price calculator",
    "beauty",
    "portal login",
    "dip powder starter kit",
    "standard bulk and natural foods",
    "monitor",
    "ア 炎天",
    "striker gunvolt",
    "color",
    "系うがい薬",
    "virtual desktop",
    "fundamentals",
    "sql database",
    "st",
    "コスプレ",
    "料金計算ツール",
  ],
  AWS: [
    "amplify",
    "t",
    "cli install windows",
    "certificate manager",
    "worth railway station",
    "saa",
    "cloud practitioner study guide 2022",
    "tats",
    ".amazon.com",
    "認定",
    "waf",
    "glue",
    "(band)",
    "の基本 仕組み 重要用語が全部わかる教科書",
    "outage",
    "certified solutions architect associate",
    "aespa",
    "クラウドプラクティショナー",
    "jobs",
    "ソリューションアーキテクト アソシエイト",
    "デベロッパー アソシエイト",
    "cloud9",
    "sap",
    "asian kung-fu generation",
    "lambda",
    "accy",
    "rds",
    "japan",
    "elemental",
    "elastic beanstalk",
    "ome clean",
    "console login",
    "management console",
    "skill builder",
    "interview questions",
    "cdk",
    "d-80",
    "hx",
    "hawanga",
    "ensors",
    "ec2",
    "solutions architect associate",
    "cloud practitioner",
    "scale",
    "s3",
    "aska",
    "ソリューションアーキテクト プロフェッショナル",
    "i rasu",
    "ソリューションアーキテクト",
    "certified cloud practitioner",
    "cloud practitioner certification",
    "awesome city club",
    "careers",
    "cm",
    "amazon",
    "コンソール",
    "awa (音楽配信)",
  ],
  GCP: [
    "gcノベルズ",
    "(曖昧さ回避)",
    "甘草片",
    "anthos",
    "ay login",
    "d shirt",
    "data engineer",
    "edia",
    "so",
    "省令",
    "l county public library",
    "aws",
    "gccr",
    "cost",
    "gcb47",
    "ガイダンス",
    "solution",
    "load balancer",
    "file server",
    "student living",
    "gp2",
    "l",
    "プロジェクト",
    "noco 1",
    "gca (企業)",
    "フリーダム",
    "パスポート",
    "security",
    "fefn9eq0",
    "azure aws",
    "region",
    "lug",
    "gcプリニア替えブラシ",
    "治験",
    "d",
    "dataflow",
    "cloud run",
    "gcse",
    "gcプレス",
    "flea deterrent for dogs",
    "ii",
    "gc含量",
    "flea deterrent for cats",
    "s employee portal",
    "all natural flea, tick and mosquito deterrent for cats",
    "ay.com login",
    "1",
    "terraform",
    "web server",
    "s",
    "applied technologies",
    "infrastructure investments",
    "ay",
    "gcペースト",
    "o",
    "vps",
    "治験使用薬",
    "web hosting",
    "host website",
    "ay.com",
    "の教科書",
    "tutorial for beginners",
    "associate cloud engineer",
    "platform",
    "s parent portal",
    "料金計算",
    "server",
    "website",
    "bigquery",
    "s eclass",
    "google",
    "vpc",
    "backup",
    "compute",
  ],
  Heroku: [
    "hero music entertainment",
    "heroquest (role-playing game)",
    "herou long sleeve tops for women",
    "hirokuntv",
    "deploy",
    "connect",
    "logs",
    "alternatives",
    "herou women long sleeve crop top turtleneck soft lightweight",
    "salesforce",
    "react",
    "app unblocker",
    "heroumbili",
    "hero",
    "herou tops for women",
    "django deployment",
    "git",
    "scheduler",
    "redis",
    "herou dresses",
    "herou casual summer short sleeve",
    "hero dress",
    "download",
    "heroquest",
    "herou shirts for women",
    "代替",
    "herobust",
    "php",
    "dashboard",
    "ん",
    "cli download",
    "hercules seghers",
    "herou dresses women",
    "hero杭全",
    "heroquest ii: legacy of sorasil",
    "deployment",
    "database",
    "hosting",
    "herculaneum",
    "flask",
    "ではじめるrailsプログラミング入門",
    "vs aws",
    "hero-u: rogue to redemption",
    "node js",
    "heroquest (video game)",
    "無料",
    "procfile",
    "python",
    "app.com",
    "rails",
    "postgres",
    "docker",
    "pricing",
    "リップ",
    "mysql",
    ".com",
    "デプロイ",
    "www..com",
    "free",
    "toolbelt",
    "github",
    "django",
    "app",
    "herou summer women casual short sleeve tops",
  ],
};
